image: maven:3.8.5-openjdk-17-slim

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - maven
        script:
          - mvn clean test
          - mvn clean package