version: "3.3"
services:
  gra:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: patricmaffi/golden-raspberry-awards
    container_name: gra
    command: java -jar -Dspring.profiles.active=dev GoldenRaspberryAwards-0.0.1-SNAPSHOT.jar
    restart: "no"
    ports:
      - "8080:8080"
    environment:
      APPLICATION_ENV: "prd"